### ISSUE TITLE
Upgrade from 1.2.1 to 2.0 - missing class error

### ISSUE THREAD

**Issue by Gomez** [plone/plone.app.multilingual#183]
I have a site with p.a.multilingual 1.2.1 and want to upgrade to 2.0 and than further to Plone5. My sites uses dexterity with p.a.contenttypes. 

Steps done:
Removed (from buildout):
```
plone.app.multilingual = 1.2.1
plone.multilingual = 1.2.1
plone.multilingualbehavior = 1.2
archetypes.multilingual = 1.2
```
Added:
```
plone.app.multilingual = 2
archetypes.multilingual = 2
```

After bin/buildout i get this error and cant even enter the ZMI:
```
2015-09-19 15:52:31 ERROR ZServerPublisher exception caught
Traceback (most recent call last):
  File "/home/gomez/.cache/buildout/eggs/Zope2-2.13.22-py2.7.egg/ZServer/PubCore/ZServerPublisher.py", line 31, in __init__
    response=b)
  File "/home/gomez/.cache/buildout/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/Publish.py", line 455, in publish_module
    environ, debug, request, response)
  File "/home/gomez/.cache/buildout/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/Publish.py", line 276, in publish_module_standard
    if request is not None: request.close()
  File "/home/gomez/.cache/buildout/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/BaseRequest.py", line 218, in close
    notify(EndRequestEvent(None, self))
  File "/home/gomez/.cache/buildout/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/home/gomez/.cache/buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/home/gomez/.cache/buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/home/gomez/.cache/buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/home/gomez/.cache/buildout/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 860, in setstate
    self._setstate(obj)
  File "/home/gomez/.cache/buildout/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 914, in _setstate
    self._reader.setGhostState(obj, p)
  File "/home/gomez/.cache/buildout/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/serialize.py", line 612, in setGhostState
    state = self.getState(pickle)
  File "/home/gomez/.cache/buildout/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/serialize.py", line 605, in getState
    return unpickler.load()
  File "/home/gomez/dotfiles/virtualenvs/xxxx/lib/python2.7/copy_reg.py", line 48, in _reconstructor
    obj = object.__new__(cls)
TypeError: ('object.__new__(LanguageIndependentModifier) is not safe, use Persistence.Persistent.__new__()', <function _reconstructor at 0x7f7fc6898b18>, (<class 'plone.multilingualbehavior.subscriber.LanguageIndependentModifier'>, <type 'object'>, None))
```
If i add back the plone.multilingualbehavior egg and resolve a ConfilctError it will work again and i can upgrade. 
Is there a way to fix this?

**Comment by bsuttor** [comment]
I made some works on this, I added an uninstall profile for plone.multilingualbehavior. After runing it, you could remove plone.multilingualbehavior from your buildout.
I will make a pull request soon 

https://github.com/IMIO/plone.multilingualbehavior/

**Comment by Gomez** [comment]
fixed by @bsuttor
