### ISSUE TITLE
AttributeError: REQUEST when i paste a Folder

### ISSUE THREAD

**Issue by 1letter** [plone/plone.app.multilingual#260]
Plone Version 4.3.11.
p.a.m Version 2.0.2

I get an Error in Version 2.0.2 if i paste a Folder in another Place of my Plone Instance.

```
Exception during pasting
Traceback (most recent call last):
  File "Script (Python)", line 13, in folder_paste
  File "/opt/Plone-4.3.3/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/OFS/CopySupport.py", line 233, in manage_pasteObjects
    notify(ObjectCopiedEvent(ob, orig_ob))
  File "/opt/Plone-4.3.3/buildout-cache/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/opt/Plone-4.3.3/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/opt/Plone-4.3.3/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/opt/Plone-4.3.3/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/opt/Plone-4.3.3/buildout-cache/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/opt/Plone-4.3.3/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 32, in objectEventNotify
    zope.component.subscribers((event.object, event), None)
  File "/opt/Plone-4.3.3/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/opt/Plone-4.3.3/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/opt/Plone-4.3.3/buildout-cache/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/opt/Plone-4.3.3/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/OFS/subscribers.py", line 132, in dispatchObjectCopiedEvent
    dispatchToSublocations(ob, event)
  File "/opt/Plone-4.3.3/buildout-cache/eggs/zope.container-3.11.2-py2.7-linux-x86_64.egg/zope/container/contained.py", line 153, in dispatchToSublocations
    for ignored in zope.component.subscribers((sub, event), None):
  File "/opt/Plone-4.3.3/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/opt/Plone-4.3.3/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/opt/Plone-4.3.3/buildout-cache/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/opt/Plone-4.3.3/buildout-cache/eggs/plone.app.multilingual-2.0.2-py2.7.egg/plone/app/multilingual/subscriber.py", line 131, in createdEvent
    if (not IPloneAppMultilingualInstalled.providedBy(obj.REQUEST)):
AttributeError: REQUEST
```
obj is a Portal Type Document, with no REQUEST Attribute. Can anoyone fix [this](https://github.com/plone/plone.app.multilingual/blob/2.x/src/plone/app/multilingual/subscriber.py#L133):
`if (not IPloneAppMultilingualInstalled.providedBy(obj.REQUEST)):`
 with
`if (not IPloneAppMultilingualInstalled.providedBy(getattr(obj, 'REQUEST', getRequest())):`

Best Regards, i'm not a Core Developer.

**Comment by 1letter** [comment]
Sorry, i see its a [Pull Request](https://github.com/plone/plone.app.multilingual/pull/259) available for the Bug. Best Regards.

**Comment by datakurre** [comment]
Thanks. So, I understood this was fixed already in https://github.com/plone/plone.app.multilingual/pull/259
